language: java
version: 1.8
os: Windows10
buildpath: HOME
env:
   - HOME: "D"
   - TRAVIS_BUILD_DIR: "D"
cache:
  directories:
    - $HOME/.cache
script: 
 - mvn compile
 - mvn package
 github_url:https://github.com/SujataDarekar/MavenPlugin
after_success:
 - git commit /home/travis/build/SujataDarekar/MavenPlugin/target/bw6-maven-plugin-1.2.2.jar -m "tets"
 - git push origin $github_url

