language: java
version: 1.8
OS: Windows10
buildpath: HOME
env:
   - HOME: "D:/EAR"
cache:
  directories:
    - $HOME/.cache
script: 
 - mvn compile
 - mvn package -Ddir="https://github.com/SujataDarekar/MavenPlugin/tree/master/src/main/java/com/tibco/bw/maven/plugin/build"
