language: java
version: 1.7
sudo: false
os: Windows10
buildpath: HOME
services:
- docker
env:
   - HOME: "C:/Users/sdarekar"
   - TRAVIS_BUILD_DIR: "D"
#deploy:
  #provider: script
 # script: "mvn package && cp /home/travis/build/SujataDarekar/MavenPlugin/target/bw6-maven-plugin-1.2.2.jar https://github.com/SujataDarekar/MavenPlugin/tree/master"
  #skip_cleanup: true
  #on:
   # tags: false
    
cache:
  directories:
  - "$HOME/.cache"
 
script: 
 - mvn compile
 - mvn package
 - make dist
deploy:
  provider: releases
  api_key:$GITHUB_API_KEY
   file: release.zip
  skip_cleanup: true
  on: tags

after_success:
 - git commit /home/travis/build/SujataDarekar/MavenPlugin/target/bw6-maven-plugin-1.2.2.jar -m "tets"
 - git push origin https://github.com/SujataDarekar/MavenPlugin.git

