language: java
version: 1.7
sudo: false
os: Windows10
buildpath: HOME
services:
- docker
env:
   - HOME: "D"
   - TRAVIS_BUILD_DIR: "D"
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true
    
cache:
  directories:
  - "$HOME/.cache"

script: 
 - mvn compile
 - mvn package

after_success:
 - git commit /home/travis/build/SujataDarekar/MavenPlugin/target/bw6-maven-plugin-1.2.2.jar -m "tets"
 - git push --branch=master https://github.com/SujataDarekar/MavenPlugin.git

