language: java
version: 1.7
sudo: false
os: Windows10
#buildpath: HOME
services:
- docker
#env:
  # - HOME: "C:/Users/sdarekar"
   #- TRAVIS_BUILD_DIR: "D"

  #cache:
 # directories:
  #- "$HOME/.cache"

script:
 - mvn compile
 - mvn package
 
 local_dir:C:/ZipFIleCreation/Unzip/install1
 
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
     - /home/travis/build/SujataDarekar/MavenPlugin/target/bw6-maven-plugin-1.2.2.jar
     - local_dir
  skip_cleanup: true
  on: 
  tags: false



